# Generated by Django 3.0.4 on 2022-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220725_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
