# Generated by Django 3.0.4 on 2022-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20220725_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='radius',
            field=models.PositiveIntegerField(verbose_name='Choose Radius'),
        ),
    ]
