# Generated by Django 3.0.4 on 2022-07-25 07:55

import apps.member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220725_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='radius',
            field=models.PositiveIntegerField(validators=[apps.member.models.exempt_zero], verbose_name='Choose Radius'),
        ),
    ]
