# Generated by Django 3.0.4 on 2022-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20220725_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='donate_badge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='share_badge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
