# Generated by Django 3.0.4 on 2022-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20220803_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='donate_badge',
            field=models.PositiveIntegerField(default=0, verbose_name='Donate Badges'),
        ),
        migrations.AlterField(
            model_name='member',
            name='share_badge',
            field=models.PositiveIntegerField(default=0, verbose_name='Share Badges'),
        ),
    ]
