# Generated by Django 3.0.4 on 2022-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20220803_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
