# Generated by Django 3.0.4 on 2022-08-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='uploads/profile/'),
        ),
    ]
