# Generated by Django 3.0.4 on 2022-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_member_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default_profile.png', null=True, upload_to='uploads/profile/'),
        ),
    ]
