# Generated by Django 3.0.4 on 2022-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20220805_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='uploads/profile/'),
        ),
    ]
