# Generated by Django 3.0.4 on 2022-08-17 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20220815_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
