# Generated by Django 4.1 on 2022-08-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('TY', 'Toys'), ('AP', 'Apparels'), ('BK', 'Books'), ('ST', 'Stationery'), ('FR', 'Furniture'), ('HW', 'Hardwares'), ('SN', 'Snacks'), ('EL', 'Electronics'), ('HI', 'Household_Items'), ('SP', 'Sports'), ('GR', 'Groceries'), ('OT', 'Others')], max_length=2, verbose_name='Categories')),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TY', 'Toys'), ('AP', 'Apparels'), ('BK', 'Books'), ('ST', 'Stationery'), ('FR', 'Furniture'), ('HW', 'Hardwares'), ('SN', 'Snacks'), ('EL', 'Electronics'), ('HI', 'Household_Items'), ('SP', 'Sports'), ('GR', 'Groceries'), ('OT', 'Others')], max_length=2, verbose_name='Categories')),
                ('cat_slug', models.SlugField(default=None, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Used', 'Used'), ('Unused', 'Unused'), ('Damaged', 'Damaged'), ('Others', 'Others')], max_length=7, null=True, verbose_name='Labels')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.BooleanField(default=True, verbose_name='Availability')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item')),
            ],
        ),
    ]
