# Generated by Django 3.0.4 on 2022-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220726_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('TY', 'Toys'), ('AP', 'Apparels'), ('BO', 'Books'), ('ST', 'Stationery'), ('FU', 'Furniture'), ('HW', 'Hardwares'), ('SN', 'Snacks'), ('EL', 'Electronics'), ('HI', 'Household_Items'), ('SP', 'Sports'), ('GR', 'Groceries'), ('OT', 'Others')], max_length=2, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TY', 'Toys'), ('AP', 'Apparels'), ('BO', 'Books'), ('ST', 'Stationery'), ('FU', 'Furniture'), ('HW', 'Hardwares'), ('SN', 'Snacks'), ('EL', 'Electronics'), ('HI', 'Household_Items'), ('SP', 'Sports'), ('GR', 'Groceries'), ('OT', 'Others')], max_length=2, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Used', 'Used'), ('Unused', 'Unused'), ('Damaged', 'Damaged')], max_length=7, verbose_name='Labels'),
        ),
    ]
