# Generated by Django 3.0.4 on 2022-08-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20220803_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='donate_badge',
        ),
        migrations.RemoveField(
            model_name='item',
            name='share_badge',
        ),
    ]
