# Generated by Django 3.0.4 on 2022-08-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20220803_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='donate_badge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='share_badge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
