# Generated by Django 3.0.4 on 2022-08-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20220803_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('title', 'label', 'category', 'description', 'image')},
        ),
    ]
